version: "3.4"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: xm-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - xm-mysql-data:/var/lib/mysql:z
      - /etc/localtime:/etc/localtime:ro

  cache-redis:
    image: redis:latest
    container_name: xm-cache-redis

  php-fpm:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      target: app_php
    volumes:
      - php_socket:/var/run/php
    environment:
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
      DATABASE_URL: mysql://root:123@xm-mysql:3306/xm?serverVersion=14&charset=utf8
    restart: unless-stopped
    container_name: xm-php-fpm
    links:
      - mysql
      - cache-redis

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: xm-frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: xm-nginx
    volumes:
      - php_socket:/var/run/php
    ports:
      - "80:80"
    links:
      - php-fpm
      - frontend

volumes:
  php_socket:
  xm-mysql-data:
    driver: local